# Generated by Django 4.0.3 on 2022-04-17 01:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
