# Generated by Django 4.0.3 on 2022-04-23 15:25

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give it a name', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Where the workout will take place or start. Defaults to your current location', srid=4326)),
                ('at', models.DateTimeField(blank=True, help_text="When your workout will take place. If it's a regular activity, leave this field empty and specify the regularity in the description.", null=True, verbose_name='Date and time')),
                ('need_to_take', models.TextField(blank=True, help_text='What people should take with them', max_length=500)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in minutes')),
                ('description', models.TextField(blank=True, help_text="All people need to now about this workout that hasn't yet been specified (like specific time or prerequisits...)", max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="Select the location around which it's the most convenient for you to work out on a regular basis. Leave it out, if you can't remain at one place for a long time. This info will help your neighbors to find you, and doesn't restrict you from visiting more distant locations or posting training session invitations elsewhere.", null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
