# Generated by Django 4.0.3 on 2022-04-10 07:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Select the location around which it's the most convenient for you to work out on a regular basis. Leave it out, if you can't remain at one place for a long time. This info will help your neighbors to find you, and doesn't restrict you from visiting more distant locations or posting training session invitations elsewhere.", null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
