# Generated by Django 4.0.4 on 2022-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='how_to_contact',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
