# Generated by Django 4.0.3 on 2022-04-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_workoutsession_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='at',
            field=models.DateTimeField(blank=True, help_text="When your workout will take place. If it's a regular activity, leave this field empty and specify the regularity in the description.", null=True, verbose_name='Date and time'),
        ),
    ]
