# Generated by Django 4.0.3 on 2022-04-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_workoutsession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in minutes'),
        ),
    ]
