# Generated by Django 4.0.3 on 2022-04-17 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_alter_workoutsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, help_text='Where the workout will take place or start.', srid=4326),
            preserve_default=False,
        ),
    ]
